### ISSUE TITLE
Can't Scroll on Report View (3.1.6-debug-2)

### ISSUE THREAD

**Issue by dkobia** [ushahidi/Ushahidi_Android#129]
- The app hangs and restarts when I try to scroll on a report

![screen shot 2013-05-15 at 11 01 41 am](https://f.cloud.github.com/assets/184092/508807/e270c630-bd91-11e2-87dc-fa96401ed227.png)

**Comment by eyedol** [comment]
@dkobia  Could you capture the logs if you can? and attach it to this issue. Also, which deployment are you testing against so I can play with it on my devices. It looks good here.

**Comment by dkobia** [comment]
@eyedol - testing on http://crime.mapatl.com

Here's a snippet of the error

```
05-15 14:58:13.863: E/AndroidRuntime(28116): FATAL EXCEPTION: IntentService[FetchReportsComments]
05-15 14:58:13.863: E/AndroidRuntime(28116): java.lang.NullPointerException
05-15 14:58:13.863: E/AndroidRuntime(28116):    at com.ushahidi.java.sdk.api.json.Comments.getComments(Comments.java:51)
05-15 14:58:13.863: E/AndroidRuntime(28116):    at com.ushahidi.java.sdk.api.tasks.CommentsTask.reportId(CommentsTask.java:85)
05-15 14:58:13.863: E/AndroidRuntime(28116):    at com.ushahidi.android.app.api.CommentsApi.getCommentsList(CommentsApi.java:65)
05-15 14:58:13.863: E/AndroidRuntime(28116):    at com.ushahidi.android.app.api.CommentsApi.saveComments(CommentsApi.java:105)
05-15 14:58:13.863: E/AndroidRuntime(28116):    at com.ushahidi.android.app.services.FetchReportsComments.fetchReportComments(FetchReportsComments.java:48)
05-15 14:58:13.863: E/AndroidRuntime(28116):    at com.ushahidi.android.app.services.FetchReportsComments.executeTask(FetchReportsComments.java:56)
05-15 14:58:13.863: E/AndroidRuntime(28116):    at com.ushahidi.android.app.services.SyncServices.onHandleIntent(SyncServices.java:112)
05-15 14:58:13.863: E/AndroidRuntime(28116):    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
05-15 14:58:13.863: E/AndroidRuntime(28116):    at android.os.Handler.dispatchMessage(Handler.java:99)
05-15 14:58:13.863: E/AndroidRuntime(28116):    at android.os.Looper.loop(Looper.java:137)
05-15 14:58:13.863: E/AndroidRuntime(28116):    at android.os.HandlerThread.run(HandlerThread.java:60)
05-15 14:58:13.893: E/android.os.Debug(713): !@Dumpstate > dumpstate -k -t -z -d -o /data/log/dumpstate_app_error
05-15 14:58:13.903: D/lights(713): button : 0 +
05-15 14:58:13.903: D/lights(713): button : 0 -
05-15 14:58:13.903: W/PowerManagerService(713): Timer 0x7->0x3|0x0
05-15 14:58:13.903: I/PowerManagerService(713): Ulight 0x7->0x3|0x0
05-15 14:58:13.903: D/LightsService(713): setLightLocked is called
05-15 14:58:13.913: I/dumpstate(28268): begin
05-15 14:58:14.644: I/DBG_DM(27825): [v5_1209_3_1][Line:451][xdmInitAdpWaitSystemRootingCheck] waits 18 sec
05-15 14:58:14.814: D/dalvikvm(28116): GC_CONCURRENT freed 6060K, 28% free 17415K/24135K, paused 13ms+21ms, total 116ms
05-15 14:58:15.155: I/Sensors(713): **** No Motion ****
05-15 14:58:15.645: I/DBG_DM(27825): [v5_1209_3_1][Line:451][xdmInitAdpWaitSystemRootingCheck] waits 19 sec
05-15 14:58:15.815: D/AudioStreamOutALSA(198): standby
05-15 14:58:15.815: D/ALSAModule(198): s_standby: handle 0x41e0bda8 h 0x0
05-15 14:58:15.815: E/ALSAModule(198): s_standby handle h 0x420161c8
05-15 14:58:15.966: E/SMD(191): DCD ON
05-15 14:58:16.046: D/ALSAModule(198): checkRunningHandle return false
05-15 14:58:16.046: D/alsa_ucm(198): snd_use_case_set(): uc_mgr 0x41e33fb8 identifier _verb value Inactive
05-15 14:58:16.046: D/alsa_ucm(198): Set mixer controls for HiFi enable 0
05-15 14:58:16.046: D/alsa_ucm(198): Setting mixer control: PRI_RX Audio Mixer MultiMedia1, value: 0
05-15 14:58:16.046: E/ALSAModule(198): Number of modifiers 0
05-15 14:58:16.046: E/ALSAModule(198): usecase_type is 0
05-15 14:58:16.046: D/alsa_ucm(198): snd_use_case_set(): uc_mgr 0x41e33fb8 identifier _disdev value Call Main Mic
05-15 14:58:16.046: D/alsa_ucm(198): disdev: device Call Main Mic not enabled, no need to disable
05-15 14:58:16.046: D/alsa_ucm(198): snd_use_case_set(): uc_mgr 0x41e33fb8 identifier _disdev value Speaker
05-15 14:58:16.046: D/alsa_ucm(198): Set mixer controls for Speaker enable 0
05-15 14:58:16.046: D/alsa_ucm(198): Setting mixer control: RX5 MIX1 INP1, value: ZERO
05-15 14:58:16.056: D/alsa_ucm(198): Setting mixer control: RX5 MIX1 INP2, value: ZERO
05-15 14:58:16.066: D/alsa_ucm(198): Setting mixer control: LINEOUT2 Volume, value: 0
05-15 14:58:16.066: D/alsa_ucm(198): Setting mixer control: LINEOUT4 Volume, value: 0
05-15 14:58:16.066: D/alsa_ucm(198): Setting mixer control: RX5 Digital Volume, value: 0
05-15 14:58:16.116: W/SignalStrength(713): getGsmLevel=4
05-15 14:58:16.116: W/SignalStrength(713): getLevel=4 (SignalStrength: 13 0 -120 -160 -120 -1 -1 99 2147483647 2147483647 2147483647 2147483647 gsm|lte 0x4)
05-15 14:58:16.116: W/SignalStrength(983): getGsmLevel=4
05-15 14:58:16.116: W/SignalStrength(983): getLevel=4 (SignalStrength: 13 0 -120 -160 -120 -1 -1 99 2147483647 2147483647 2147483647 2147483647 gsm|lte 0x4)
05-15 14:58:16.116: W/SignalStrength(983): getGsmLevel=4
05-15 14:58:16.116: W/SignalStrength(983): getLevel=4 (SignalStrength: 13 0 -120 -160 -120 -1 -1 99 2147483647 2147483647 2147483647 2147483647 gsm|lte 0x4)
05-15 14:58:16.116: D/STATUSBAR-NetworkController(983): onSignalStrengthsChanged signalStrength=SignalStrength: 13 0 -120 -160 -120 -1 -1 99 2147483647 2147483647 2147483647 2147483647 gsm|lte 0x4 level=4
05-15 14:58:16.116: W/AlarmManager(713): FACTORY_ON= 0
05-15 14:58:16.116: W/AlarmManager(713): FACTORY_ON= 0
05-15 14:58:16.156: I/Sensors(713): **** Motion ****
05-15 14:58:16.646: I/DBG_DM(27825): [v5_1209_3_1][Line:451][xdmInitAdpWaitSystemRootingCheck] waits 20 sec
05-15 14:58:17.037: I/InputReader(713): Touch event's action is 0x0 (deviceType=0) [pCnt=1, s=0.48877 ]
05-15 14:58:17.037: D/lights(713): button : 255 +
05-15 14:58:17.037: D/lights(713): button : 255 -
05-15 14:58:17.037: I/PowerManagerService(713): Ulight 0x3->0x7|0x0
05-15 14:58:17.037: D/LightsService(713): setLightLocked is called
05-15 14:58:17.187: I/InputReader(713): Touch event's action is 0x1 (deviceType=0) [pCnt=1, s=]
05-15 14:58:17.357: E/Sensors(713): accelHandler 0.231119 7.734715 7.362290
05-15 14:58:17.647: D/STATUSBAR-NetworkController(983): refreshSignalCluster:0
05-15 14:58:17.647: D/STATUSBAR-SignalClusterView(983): mSeparateMobileGroup=8
05-15 14:58:17.647: D/STATUSBAR-SignalClusterView(983): mSeparateMobileGroup=8
05-15 14:58:17.647: I/DBG_DM(27825): [v5_1209_3_1][Line:451][xdmInitAdpWaitSystemRootingCheck] waits 21 sec
05-15 14:58:17.647: D/STATUSBAR-SignalClusterView(983): mSeparateMobileGroup=8
05-15 14:58:17.687: D/overlay(195): FROM_STATE = OV_BYPASS_2_LAYER TO_STATE = OV_CLOSED
05-15 14:58:17.687: D/overlay(195): FROM_STATE = OV_CLOSED TO_STATE = OV_BYPASS_2_LAYER
05-15 14:58:18.528: D/lights(713): button : 0 +
05-15 14:58:18.528: D/lights(713): button : 0 -
05-15 14:58:18.528: W/PowerManagerService(713): Timer 0x7->0x3|0x0
05-15 14:58:18.528: I/PowerManagerService(713): Ulight 0x7->0x3|0x0
05-15 14:58:18.528: D/LightsService(713): setLightLocked is called
05-15 14:58:18.608: E/MP-Decision(1581): DOWN Ld:8 Ns:1.100000 Ts:190 rq:0.400000 seq:196.000000
05-15 14:58:18.638: I/DBG_DM(27825): [v5_1209_3_1][Line:451][xdmInitAdpWaitSystemRootingCheck] waits 22 sec
05-15 14:58:18.879: D/KeyguardViewMediator(713): setHidden false
05-15 14:58:18.899: D/KeyguardViewMediator(713): setHidden false
05-15 14:58:18.969: E/SMD(191): DCD ON
05-15 14:58:18.989: D/overlay(195): FROM_STATE = OV_BYPASS_2_LAYER TO_STATE = OV_CLOSED
05-15 14:58:19.189: D/overlay(195): FROM_STATE = OV_CLOSED TO_STATE = OV_BYPASS_1_LAYER
05-15 14:58:19.249: D/KeyguardViewMediator(713): setHidden false
05-15 14:58:19.259: D/KeyguardViewMediator(713): setHidden false
05-15 14:58:19.649: I/DBG_DM(27825): [v5_1209_3_1][Line:451][xdmInitAdpWaitSystemRootingCheck] waits 23 sec
05-15 14:58:19.649: D/STATUSBAR-NetworkController(983): refreshSignalCluster:0
05-15 14:58:19.649: D/STATUSBAR-SignalClusterView(983): mSeparateMobileGroup=8
05-15 14:58:19.649: D/STATUSBAR-SignalClusterView(983): mSeparateMobileGroup=8
05-15 14:58:19.649: D/STATUSBAR-SignalClusterView(983): mSeparateMobileGroup=8
05-15 14:58:20.160: D/VoldCmdListener(180): asec list
05-15 14:58:20.651: I/DBG_DM(27825): [v5_1209_3_1][Line:451][xdmInitAdpWaitSystemRootingCheck] waits 24 sec
05-15 14:58:20.661: D/STATUSBAR-NetworkController(983): refreshSignalCluster:0
05-15 14:58:20.661: D/STATUSBAR-SignalClusterView(983): mSeparateMobileGroup=8
05-15 14:58:20.661: D/STATUSBAR-SignalClusterView(983): mSeparateMobileGroup=8
05-15 14:58:20.661: D/STATUSBAR-SignalClusterView(983): mSeparateMobileGroup=8
05-15 14:58:20.691: I/dumpstate(28268): done
05-15 14:58:20.711: I/com.ushahidi.android.app.util.Util(28116): onPause
05-15 14:58:20.711: D/PowerManagerService(713): acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1026000  uid : 1000  pid : 713  tag : ActivityManager
05-15 14:58:20.721: I/power(713): *** acquire_dvfs_lock : lockType : 1  freq : 1026000 
05-15 14:58:20.721: W/ActivityManager(713): mDVFSLock.acquire()
05-15 14:58:20.771: D/STATUSBAR-StatusBarManagerService(713): setSystemUiVisibility(0x0)
05-15 14:58:20.771: D/STATUSBAR-StatusBarManagerService(713): manageDisableList what=0x0 pkg=WindowManager.LayoutParams
05-15 14:58:20.791: D/KeyguardViewMediator(713): setHidden false
05-15 14:58:20.811: I/com.ushahidi.android.app.util.Util(28116): onActivityResult
05-15 14:58:20.811: I/com.ushahidi.android.app.util.Util(28116): onRestart
05-15 14:58:20.811: I/com.ushahidi.android.app.util.Util(28116): onStart
05-15 14:58:20.811: I/com.ushahidi.android.app.util.Util(28116): onResume
05-15 14:58:20.831: V/WindowOrientationListener(713): nearestRotation : 0   Angle: 358   tilt: 42
05-15 14:58:20.861: I/SurfaceFlinger(195): id=23921(5523) createSurf 0x48aa7d84 (1x1),1 flag=0
05-15 14:58:20.861: D/KeyguardViewMediator(713): setHidden false
05-15 14:58:20.871: D/overlay(195): FROM_STATE = OV_BYPASS_1_LAYER TO_STATE = OV_CLOSED
05-15 14:58:20.881: D/overlay(195): FROM_STATE = OV_CLOSED TO_STATE = OV_BYPASS_1_LAYER
05-15 14:58:20.881: I/InputDispatcher(713): Delivering touch to current input target: action: 0x0
05-15 14:58:20.881: I/InputDispatcher(713): Delivering touch to current input target: action: 0x0
05-15 14:58:20.881: I/InputDispatcher(713): Delivering touch to current input target: action: 0x0
05-15 14:58:20.881: D/KeyguardViewMediator(713): setHidden false
05-15 14:58:20.891: W/SignalStrength(713): getDbm 1
05-15 14:58:20.891: W/SignalStrength(713): getGsmDbm=-87
05-15 14:58:20.891: W/SignalStrength(713): getDbm=-87
05-15 14:58:20.891: W/SignalStrength(713): getAsuLevel 1
05-15 14:58:20.891: W/SignalStrength(713): getGsmAsuLevel=13
05-15 14:58:20.891: W/SignalStrength(713): getAsuLevel=13
05-15 14:58:20.911: I/InputDispatcher(713): Delivering touch to current input target: action: 0x1
05-15 14:58:20.911: I/InputDispatcher(713): Delivering touch to current input target: action: 0x1
05-15 14:58:20.911: I/InputDispatcher(713): Delivering touch to current input target: action: 0x1
05-15 14:58:20.921: E/MP-Decision(1581): UP Ld:58 Nw:1.990000 Tw:140 rq:4.300000 seq:186.000000
05-15 14:58:20.921: W/SurfaceView(28116): CHECK surface infomation creating=false formatChanged=false sizeChanged=false visible=false visibleChanged=true surfaceChanged=true realSizeChanged=false redrawNeeded=false left=false top=false
05-15 14:58:20.921: I/SurfaceFlinger(195): id=23919 Removed idx=3 MapSz=6
05-15 14:58:20.921: I/SurfaceFlinger(195): id=23919 Removed idx=-2 MapSz=6
05-15 14:58:20.921: D/KeyguardViewMediator(713): setHidden false
05-15 14:58:20.921: D/KeyguardViewMediator(713): setHidden false
05-15 14:58:20.931: I/Adreno200-EGLSUB(195): <CreateImage:897>: Android Image
05-15 14:58:20.931: I/Adreno200-EGLSUB(195): <GetImageAttributes:1106>: RGBA_8888
05-15 14:58:20.931: W/SurfaceView(28116): CHECK surface infomation creating=false formatChanged=false sizeChanged=false visible=false visibleChanged=true surfaceChanged=true realSizeChanged=false redrawNeeded=false left=false top=false
05-15 14:58:20.931: I/SurfaceFlinger(195): id=23920 Removed idx=3 MapSz=5
05-15 14:58:20.931: I/SurfaceFlinger(195): id=23920 Removed idx=-2 MapSz=5
05-15 14:58:20.931: I/SurfaceFlinger(195): id=23918 Removed idx=3 MapSz=4
```
