### ISSUE TITLE
Force closing after sending successful checkin

### ISSUE THREAD

**Issue by bfazen** [ushahidi/Ushahidi_Android#53]
I am getting a consistent FC with Ushahidi 2.9.4 interacting with a CrowdMap deployment using checkins.  The checkin sends fine, but when app goes to clearFields, it seems like clearing the image file (which was never loaded in the first place) causes the FC?

```
05-13 13:15:19.245: E/AndroidRuntime(6208): FATAL EXCEPTION: main
05-13 13:15:19.245: E/AndroidRuntime(6208): java.lang.NullPointerException
05-13 13:15:19.245: E/AndroidRuntime(6208):     at java.io.File.fixSlashes(File.java:234)
05-13 13:15:19.245: E/AndroidRuntime(6208):     at java.io.File.init(File.java:201)
05-13 13:15:19.245: E/AndroidRuntime(6208):     at java.io.File.<init>(File.java:152)
05-13 13:15:19.245: E/AndroidRuntime(6208):     at com.ushahidi.android.app.checkin.CheckinActivity.clearFields(CheckinActivity.java:318)
05-13 13:15:19.245: E/AndroidRuntime(6208):     at com.ushahidi.android.app.checkin.CheckinActivity.access$6(CheckinActivity.java:315)
05-13 13:15:19.245: E/AndroidRuntime(6208):     at com.ushahidi.android.app.checkin.CheckinActivity$1.run(CheckinActivity.java:584)
05-13 13:15:19.245: E/AndroidRuntime(6208):     at android.os.Handler.handleCallback(Handler.java:587)
05-13 13:15:19.245: E/AndroidRuntime(6208):     at android.os.Handler.dispatchMessage(Handler.java:92)
05-13 13:15:19.245: E/AndroidRuntime(6208):     at android.os.Looper.loop(Looper.java:123)
05-13 13:15:19.245: E/AndroidRuntime(6208):     at android.app.ActivityThread.main(ActivityThread.java:4627)
05-13 13:15:19.245: E/AndroidRuntime(6208):     at java.lang.reflect.Method.invokeNative(Native Method)
05-13 13:15:19.245: E/AndroidRuntime(6208):     at java.lang.reflect.Method.invoke(Method.java:521)
05-13 13:15:19.245: E/AndroidRuntime(6208):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
05-13 13:15:19.245: E/AndroidRuntime(6208):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
05-13 13:15:19.245: E/AndroidRuntime(6208):     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by eyedol** [comment]
@bfazen -- Will look into this

**Comment by eyedol** [comment]
Fixed
